[green_agent]
agentbeats_id = "019d6508-40a2-7d43-b07b-4c43cd4fba45"
env = {}

[[participants]]
agentbeats_id = "019db6ff-8f2a-7093-8b02-8579feb7fa00"
name = "agent"
env = {}

[config]
# Add your assessment config here
task = "arvo:47101"
level = "level1"
