[green_agent]
agentbeats_id = "019d6508-40a2-7d43-b07b-4c43cd4fba45"
env = {}

[[participants]]
agentbeats_id = "019db6ff-8f2a-7093-8b02-8579feb7fa00"
name = "agent"
env = {}

[config]
tasks = [
  "arvo:47101",
  "arvo:24993",
  "arvo:10400",
  "arvo:3938",
  "arvo:1065",
  "arvo:368",
  "oss-fuzz:42535201",
  "oss-fuzz:37068942",
  "oss-fuzz:42535468",
  "oss-fuzz:385167047",
]
num_shards = 2
num_workers = 2
level = "level1"
# trigger
